### ISSUE TITLE
v1.0.2 doesn't appear in Arduino IDE

### ISSUE THREAD

**Issue by SirWilliamT** [sparkfun/Qwiic_Capacitive_Touch_Slider_Arduino_Library#1]
### Subject of the issue
The Arduino IDE only shows version 1.0.0 in the Library Manager with no option to install the latest.

### Your workbench
Arduino IDE (PC)

### Steps to reproduce
Open Arduino IDE.
Go to Tools > Manage Libraries...
Search for "CAP1203"
Note that it only shows version 1.0.0 and you can't update.

### Expected behaviour
Should see 1.0.2 as an option to update to in the Library Manager in Arduino IDE.

### Actual behaviour
Only shows version 1.0.0 in library manager.

**Comment by nseidle** [comment]
Ugh. Sorry, the repo and library name don't match so the Arduino lib robot is not picking up the changes. I'll change the lib name and release. Please let me know if you see v1.0.3 shortly.

For my notes: [original request](https://github.com/arduino/Arduino/issues/8799) with name "Qwiic_Capacitive_Touch_Slider_Arduino_Library"

**Comment by nseidle** [comment]
Hmm - still not working. Might be the lack of ['v' in the version](https://github.com/sparkfun/Qwiic_Capacitive_Touch_Slider_Arduino_Library/commit/3c7b06a3234f553489baf6d9b40785352c0a0082). We shall see.

**Comment by SirWilliamT** [comment]
Strangely still not picking up the latest. Still shows 1.0.0 when I delete it from my library and try to redownload it.

**Comment by SirWilliamT** [comment]
I am not seeing anything wrong in the library properties as far as I can tell.

**Comment by nseidle** [comment]
Yea, dunno. I've pinged Arduino to see if they can spot the error.

**Comment by nseidle** [comment]
After [much shuffling](https://github.com/arduino/Arduino/issues/11493#issuecomment-839261776) I can see v1.0.5 in the lib manager. Please have a look. Thanks for reporting. Please open a new issue if you see any other issues.

**Comment by SirWilliamT** [comment]
Thanks, Nathan, for sorting this out! I also learned a little bit more about libraries in Arduino IDE in the process. ;)
